const PATH = {
  assets: "./assets/",
  mobdrop: "../items/mob_drops/images/",
  avatar: "../avatar/",
  list: "../item_list/template/"
};
const DATA = [
/*
{
  name: "Tesuchi Scales",
  layer: "l0 l1 l2 l3 l4 l5", // multiple badges
  mob: "Tesuchi",

  image: PATH.mobdrop + "tesuchi_scales.png",
  rarity: "",
  description: "Crispy",


trades: [
{
  input1: PATH.mobdrop + "tesuchi_scales.png",
  input2: PATH.mobdrop + "tesuchi_scales.png",
  output: PATH.mobdrop + "orth_coin.png",

  name1: "Tesuchi Scale",
  name2: "Tesuchi Scale",
  outputName: "Orth Coin",

  link1: PATH.list + "tesuchi_scale.html",
  link2: PATH.list + "tesuchi_scale.html",
  outputLink: PATH.list + "orth_coin.html"
}
],

  tips: [
    {
      avatar: PATH.avatar + "block_oc.png",
      text: "When eating it gives a saturation of 1.2 and a nutrition of 2 important for getting netherite armor."
    }
  ],

  recipes: [
  {
  grid: [
    PATH.mobdrop + "tesuchi_scales.png","","",
    PATH.mobdrop + "","","",
    PATH.mobdrop + "","",""
  ],
  names: [
    "Tesuchi Scale","","",
    "","","",
    "","",""
  ],

  links: [   
    PATH.list + "tesuchi_scale.html","","",
    PATH.list + "","","",
    PATH.list + "","",""
  ],

  output: PATH.mobdrop + "orth_coin.png",
  outputName: "Orth Coin",
  outputLink: PATH.list + "orth_coin.html"
  }
  ]
},
67 haha */
{
  name: "Abyssal Snail Gunk",
  layer: "l5",
  mob: "Abyssal Snail",
  mobLink: "/bestiary/bestiary.html?page=78",
  image: "../items/mob_drops/images/abyssal_snail_gunk.png",
  rarity: "",
  description: "Many delvers feel strangely compelled to lick slime such as this. Well, DON'T!",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Abyssal Snail Shell",
  layer: "l5",
  mob: "Abyssal Snail",
  mobLink: "/bestiary/bestiary.html?page=78",
  image: "../items/mob_drops/images/abyssal_snail_shell.png",
  rarity: "",
  description: "If you put it to your ear, you might hear the wailing of the souls lost to the sea.",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Ashimite Antlers",
  layer: "l5",
  mob: "Ashimite",
  mobLink: "/bestiary/bestiary.html?page=79",
  image: "../items/mob_drops/images/ashimite_antlers.png",
  rarity: "",
  description: "They use these to assert dominance. Yet they run off when you get close...",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Ashimite Hoof",
  layer: "l5",
  mob: "Ashimite",
  mobLink: "/bestiary/bestiary.html?page=79",
  image: "../items/mob_drops/images/ashimite_hoof.png",
  rarity: "",
  description: "Excellent for starting fires!",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Raw Ashimite Meat",
  layer: "l5",
  mob: "Ashimite",
  mobLink: "/bestiary/bestiary.html?page=79",
  image: "../items/mob_drops/images/ashimite_meat_raw.png",
  rarity: "",
  description: "Seems like a great source of food.",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Cooked Ashimite Meat",
  layer: "l5",
  mob: "Ashimite",
  mobLink: "/bestiary/bestiary.html?page=79",
  image: "../items/mob_drops/images/ashimite_meat_cooked.png",
  rarity: "",
  description: "Very tasty and rich in nutrients!",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Beniguma Fur",
  layer: "l1",
  mob: "Beniguma",
  mobLink: "/bestiary/bestiary.html?page=2",
  image: "../items/mob_drops/images/beniguma_fur.png",
  rarity: "",
  description: "This used to be a cute fox-like creature...",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Raw Billabonk Leg",
  layer: "l2",
  mob: "Billabonk",
  mobLink: "/bestiary/bestiary.html?page=17",
  image: "../items/mob_drops/images/billabonk_leg_raw.png",
  rarity: "",
  description: "Do the stanky leg",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Cooked Billabonk Leg",
  layer: "l2",
  mob: "Billabonk",
  mobLink: "/bestiary/bestiary.html?page=17",
  image: "../items/mob_drops/images/billabonk_leg_cooked.png",
  rarity: "",
  description: "Moves when you apply electricity.",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Buroguro Lantern",
  layer: "l3",
  mob: "Buroguro",
  mobLink: "/bestiary/bestiary.html?page=44",
  image: "../items/mob_drops/images/buroguro_lantern.png",
  rarity: "",
  description: "Seems to be poisonous. I best not eat it...",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Buroguro Stinger",
  layer: "l3",
  mob: "Buroguro",
  mobLink: "/bestiary/bestiary.html?page=44",
  image: "../items/mob_drops/images/buroguro_stinger.png",
  rarity: "",
  description: "It's still drippin'!",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Raw Chikyuoebi",
  layer: "l5",
  mob: "Chikyuoebi",
  mobLink: "/bestiary/bestiary.html?page=80",
  image: "../items/mob_drops/images/chikyuoebi_raw.png",
  rarity: "",
  description: "Not that tasty raw...",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Cooked Chikyuoebi Claw",
  layer: "l5",
  mob: "Chikyuoebi",
  mobLink: "/bestiary/bestiary.html?page=80",
  image: "../items/mob_drops/images/chikyuoebi_cooked.png",
  rarity: "",
  description: "Tastes like lobster!",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Chimokami Fang",
  layer: "l2",
  mob: "Chimokami",
  mobLink: "/bestiary/bestiary.html?page=18",
  image: "../items/mob_drops/images/chimokami_fang.png",
  rarity: "",
  description: "It is said that these beasts house a spiritual fire within.",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Chimokami Tail",
  layer: "l2",
  mob: "Chimokami",
  mobLink: "/bestiary/bestiary.html?page=18",
  image: "../items/mob_drops/images/chimokami_tail.png",
  rarity: "",
  description: "These critters like darkness.",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Corpse-Weeper Eye",
  layer: "l2",
  mob: "Corpse-Weeper",
  mobLink: "/bestiary/bestiary.html?page=19",
  image: "../items/mob_drops/images/corpse_weeper_eye.png",
  rarity: "",
  description: "It feels like it's staring into your soul...",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Corpse-Weeper Feather",
  layer: "l2",
  mob: "Corpse-Weeper",
  mobLink: "/bestiary/bestiary.html?page=19",
  image: "../items/mob_drops/images/corpse_weeper_feather.png",
  rarity: "",
  description: "A quill for writing in blood.",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Raw Corpse-Weeper Meat",
  layer: "l2",
  mob: "Corpse-Weeper",
  mobLink: "/bestiary/bestiary.html?page=19",
  image: "../items/mob_drops/images/corpse_weeper_meat_raw.png",
  rarity: "",
  description: "It both smells and tastes horrible... Will cooking this help?",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Cooked Corpse-Weeper Meat",
  layer: "l2",
  mob: "Corpse-Weeper",
  mobLink: "/bestiary/bestiary.html?page=19",
  image: "../items/mob_drops/images/corpse_weeper_meat_cooked.png",
  rarity: "",
  description: "The stench is awful but it tastes so good...",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Cyatoria Feather",
  layer: "l1 l2",
  mob: "Cyatoria",
  mobLink: "/bestiary/bestiary.html?page=3",
  image: "../items/mob_drops/images/cyatoria_feather.png",
  rarity: "",
  description: "It resembles the feathers of a Sakawatari...",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Raw Cyatoria Drumstick",
  layer: "l1 l2",
  mob: "Cyatoria",
  mobLink: "/bestiary/bestiary.html?page=3",
  image: "../items/mob_drops/images/cyatoria_drumstick_raw.png",
  rarity: "",
  description: "Said to be the offspring of a rare creature originating from the 7th Layer, The Final Maelstrom. I assure you, it tastes just like chicken...",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Cooked Cyatoria Drumstick",
  layer: "l1 l2",
  mob: "Cyatoria",
  mobLink: "/bestiary/bestiary.html?page=3",
  image: "../items/mob_drops/images/cyatoria_drumstick_cooked.png",
  rarity: "",
  description: "Said to be the offspring of a rare creature originating from the 7th Layer, The Final Maelstrom. I assure you, it tastes just like chicken...",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Daikonchu Carapace",
  layer: "l3",
  mob: "Daikonchu",
  mobLink: "/bestiary/bestiary.html?page=45",
  image: "../items/mob_drops/images/daikonchu_carapace.png",
  rarity: "",
  description: "I could totally wear this.",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Daikonchu Wing",
  layer: "l3",
  mob: "Daikonchu",
  mobLink: "/bestiary/bestiary.html?page=45",
  image: "../items/mob_drops/images/daikonchu_wing.png",
  rarity: "",
  description: "They're still buzzing...",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Raw Demonfish",
  layer: "l5",
  mob: "Demonfish",
  mobLink: "/bestiary/bestiary.html?page=81",
  image: "../items/mob_drops/images/demonfish_raw.png",
  rarity: "",
  description: "Imagine the shame of getting flopped to death by one of these.",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Cooked Demonfish",
  layer: "l5",
  mob: "Demonfish",
  mobLink: "/bestiary/bestiary.html?page=81",
  image: "../items/mob_drops/images/demonfish_cooked.png",
  rarity: "",
  description: "A staple food among delvers.",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Dosetori Bone",
  layer: "l2 l3",
  mob: "Dosetori",
  mobLink: "/bestiary/bestiary.html?page=21",
  image: "../items/mob_drops/images/dosetori_bone.png",
  rarity: "",
  description: "This thing sounds... hollow.",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Dosetori Wing",
  layer: "l2 l3",
  mob: "Dosetori",
  mobLink: "/bestiary/bestiary.html?page=21",
  image: "../items/mob_drops/images/dosetori_wing.png",
  rarity: "",
  description: "Its texture feels otherworldly.",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Raw Dosetori Meat",
  layer: "l2 l3",
  mob: "Dosetori",
  mobLink: "/bestiary/bestiary.html?page=21",
  image: "../items/mob_drops/images/dosetori_meat_raw.png",
  rarity: "",
  description: "Tastes like chicken.",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Cooked Dosetori Meat",
  layer: "l2 l3",
  mob: "Dosetori",
  mobLink: "/bestiary/bestiary.html?page=21",
  image: "../items/mob_drops/images/dosetori_meat_cooked.png",
  rarity: "",
  description: "Tastes like fried chicken.",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Edusan Scale",
  layer: "l5",
  mob: "Edusan",
  mobLink: "/bestiary/bestiary.html?page=82",
  image: "../items/mob_drops/images/edusan_scale.png",
  rarity: "",
  description: "Exudes a beautifully ominous aura.",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Edusan Whisker",
  layer: "l5",
  mob: "Edusan",
  mobLink: "/bestiary/bestiary.html?page=82",
  image: "../items/mob_drops/images/edusan_whisker.png",
  rarity: "",
  description: "When I touch this I start hearing voices...",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Fuwagi Foot",
  layer: "l1 l2",
  mob: "Fuwagi",
  mobLink: "/bestiary/bestiary.html?page=4",
  image: "../items/mob_drops/images/fuwagi_foot.png",
  rarity: "",
  description: "Rumor has it if you have a fuwagi foot in your inventory, you will have good luck.",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Fuwagi Hide",
  layer: "l1 l2",
  mob: "Fuwagi",
  mobLink: "/bestiary/bestiary.html?page=4",
  image: "../items/mob_drops/images/fuwagi_hide.png",
  rarity: "",
  description: "Soft and cozy. You can make some quality fabric out of this.",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Raw Fuwagi Meat",
  layer: "l1 l2",
  mob: "Fuwagi",
  mobLink: "/bestiary/bestiary.html?page=4",
  image: "../items/mob_drops/images/fuwagi_meat_raw.png",
  rarity: "",
  description: "Gamey with a hint of carrot and apple. Mostly carrot though.",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Cooked Fuwagi Meat",
  layer: "l1 l2",
  mob: "Fuwagi",
  mobLink: "/bestiary/bestiary.html?page=4",
  image: "../items/mob_drops/images/fuwagi_meat_cooked.png",
  rarity: "",
  description: "Gamey with a hint of carrot and apple. Mostly carrot though.",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Hagamizukin Tooth",
  layer: "l4 l5",
  mob: "Hagamizukin",
  mobLink: "/bestiary/bestiary.html?page=59",
  image: "../items/mob_drops/images/hagamizukin_tooth.png",
  rarity: "",
  description: "Warped and sharp like some of the tempestuous abyssal bedrock.",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Raw Hagamizukin",
  layer: "l4 l5",
  mob: "Hagamizukin",
  mobLink: "/bestiary/bestiary.html?page=59",
  image: "../items/mob_drops/images/hagamizukin_raw.png",
  rarity: "",
  description: "The meat still feels angry with me.",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Cooked Hagamizukin",
  layer: "l4 l5",
  mob: "Hagamizukin",
  mobLink: "/bestiary/bestiary.html?page=59",
  image: "../items/mob_drops/images/hagamizukin_cooked.png",
  rarity: "",
  description: "The meat still feels angry with me, but smells good now.",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Hammerbeak Beak",
  layer: "l1 l2 l4",
  mob: "Hammerbeak",
  mobLink: "/bestiary/bestiary.html?page=5",
  image: "../items/mob_drops/images/hammerbeak_beak.png",
  rarity: "",
  description: "Can be used as a fire starter when combined with a little steel. It seems sharp enough to put an eye out.",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Hammerbeak Egg",
  layer: "l1 l2 l4",
  mob: "Hammerbeak",
  mobLink: "/bestiary/bestiary.html?page=6",
  image: "../items/mob_drops/images/hammerbeak_egg.png",
  rarity: "",
  description: "Can be used as a cooking ingredient or mischievious acts of tomfoolery. Mother Hammerbeak does not look to happy...",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Hammerbeak Feather",
  layer: "l1 l2 l4",
  mob: "Hammerbeak",
  mobLink: "/bestiary/bestiary.html?page=5",
  image: "../items/mob_drops/images/hammerbeak_feather.png",
  rarity: "",
  description: "Just a feather, innit?",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Raw Hammerbeak Wing",
  layer: "l1 l2 l4",
  mob: "Hammerbeak",
  mobLink: "/bestiary/bestiary.html?page=5",
  image: "../items/mob_drops/images/hammerbeak_wing_raw.png",
  rarity: "",
  description: "This meat seems delicious if cooked properly!",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Cooked Hammerbeak Wing",
  layer: "l1 l2 l4",
  mob: "Hammerbeak",
  mobLink: "/bestiary/bestiary.html?page=5",
  image: "../items/mob_drops/images/hammerbeak_wing_cooked.png",
  rarity: "",
  description: "A staple food among delvers.",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Hashofu Body",
  layer: "l4 l5",
  mob: "Hashofu",
  mobLink: "/bestiary/bestiary.html?page=61",
  image: "../items/mob_drops/images/hashofu_body.png",
  rarity: "",
  description: "I can use this for what?",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Hashofu Eye",
  layer: "l4 l5",
  mob: "Hashofu",
  mobLink: "/bestiary/bestiary.html?page=61",
  image: "../items/mob_drops/images/hashofu_eye.png",
  rarity: "",
  description: "There is a fire in its eyes.",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Hashofu Tail",
  layer: "l4 l5",
  mob: "Hahsofu",
  mobLink: "/bestiary/bestiary.html?page=61",
  image: "../items/mob_drops/images/hashofu_tail_raw.png",
  rarity: "",
  description: "It is said it tastes like sushi. Though by it's smell I doubt it...",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Cooked Hashofu Tail",
  layer: "l4 l5",
  mob: "Hashofu",
  mobLink: "/bestiary/bestiary.html?page=61",
  image: "../items/mob_drops/images/hashofu_tail_cooked.png",
  rarity: "",
  description: "It is said it tastes like sushi. Smell isn't so unbearable anymore!",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Himushi Core",
  layer: "l3",
  mob: "Himushi",
  mobLink: "/bestiary/bestiary.html?page=47",
  image: "../items/mob_drops/images/himushi_core.png",
  rarity: "",
  description: "A powerful magma core. Could be useful in powerful relics...",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Crystal Hisoishi Claw",
  layer: "l2 l3",
  mob: "Hisoishi",
  mobLink: "/bestiary/bestiary.html?page=37",
  image: "../items/mob_drops/images/hisoishi_claw.png",
  rarity: "",
  description: "This sharp claw can dig through stone with ease.",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Hisoishi Shell",
  layer: "l2 l3",
  mob: "Hisoishi",
  mobLink: "/bestiary/bestiary.html?page=37",
  image: "../items/mob_drops/images/hisoishi_shell.png",
  rarity: "",
  description: "The shell is hard as amethyst to keep out predators.",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Hisomukuro Rib",
  layer: "l5",
  mob: "Hisomukuro",
  mobLink: "/bestiary/bestiary.html?page=85",
  image: "../items/mob_drops/images/hisomukuro_rib.png",
  rarity: "",
  description: "Its bony on the outside but Metallic on the inside! prehaps i can use this to launch something...",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Horncrier Horn",
  layer: "l4 l5",
  mob: "Horncrier",
  mobLink: "/bestiary/bestiary.html?page=62",
  image: "../items/mob_drops/images/horncrier_horn.png",
  rarity: "",
  description: "These colors are unlike anything I've encountered before.",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Raw Ikenosuke",
  layer: "l2 l3 l4",
  mob: "Ikenosuke",
  mobLink: "/bestiary/bestiary.html?page=25",
  image: "../items/mob_drops/images/ikenosuke_raw.png",
  rarity: "",
  description: "The skin was tough, but the meat... Yum!",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Cooked Ikenosuke",
  layer: "l2 l3 l4",
  mob: "Ikenosuke",
  mobLink: "/bestiary/bestiary.html?page=25",
  image: "../items/mob_drops/images/ikenosuke_cooked.png",
  rarity: "",
  description: "The skin is tough, but the meat... Yum!",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Ikonia Plate",
  layer: "l5",
  mob: "Ikonia",
  mobLink: "/bestiary/bestiary.html?page=87",
  image: "../items/mob_drops/images/ikonia_plate.png",
  rarity: "",
  description: "The skin is tough, but the meat... Yum!",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Inbyo Fur",
  layer: "l2",
  mob: "Inbyo",
  mobLink: "/bestiary/bestiary.html?page=39",
  image: "../items/mob_drops/images/inbyo_fur.png",
  rarity: "",
  description: "This stench is nauseating...",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Raw Inbyo Meat",
  layer: "l2",
  mob: "Inbyo",
  mobLink: "/bestiary/bestiary.html?page=39",
  image: "../items/mob_drops/images/inbyo_meat_raw.png",
  rarity: "",
  description: "Doesn't look very tasty...",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Cooked Inbyo Meat",
  layer: "l2",
  mob: "Inbyo",
  mobLink: "/bestiary/bestiary.html?page=39",
  image: "../items/mob_drops/images/inbyo_meat_cooked.png",
  rarity: "",
  description: "Seems more edible now, though it still smells horrid...",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Kagi Tachikiri Pincer",
  layer: "l5",
  mob: "Kagi Tachikiri",
  mobLink: "/bestiary/bestiary.html?page=88",
  image: "../items/mob_drops/images/kagi_tachikiri_pincer.png",
  rarity: "",
  description: "Extremely sharp, watch your fingers!",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Kakatsumuri Glowing Tip",
  layer: "l2",
  mob: "Kakatsumuri",
  mobLink: "/bestiary/bestiary.html?page=50",
  image: "../items/mob_drops/images/kakatsumuri_glowing_tip.png",
  rarity: "",
  description: "The very tip of the shell, it seems to leak a glowing sticky substance.",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Kakatsumuri Shell",
  layer: "l2",
  mob: "Kakatsumuri",
  mobLink: "/bestiary/bestiary.html?page=50",
  image: "../items/mob_drops/images/kakatsumuri_shell.png",
  rarity: "",
  description: "Even after death the shell still keeps it bright glow.",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Kazura Squid Ink Sac",
  layer: "l4",
  mob: "Kazura",
  mobLink: "/bestiary/bestiary.html?page=64",
  image: "../items/mob_drops/images/kazura_squid_ink_sac.png",
  rarity: "",
  description: "The sac is white, but its ink is black.",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Kuongatari Juice",
  layer: "l4 l5",
  mob: "Kuongatari",
  mobLink: "/bestiary/bestiary.html?page=65",
  image: "../items/mob_drops/images/kuongatari_juice.png",
  rarity: "",
  description: "Yuck! And it's sticky too!",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Kuongatari Silk",
  layer: "l4 l5",
  mob: "Kuongatari",
  mobLink: "/bestiary/bestiary.html?page=65",
  image: "../items/mob_drops/images/kuongatari_silk.png",
  rarity: "",
  description: "A very thin, yet surprisingly tensile strand of silk.",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Kuongatari Abdomen",
  layer: "l4 l5",
  mob: "Kuongatari",
  mobLink: "/bestiary/bestiary.html?page=65",
  image: "../items/mob_drops/images/kuongatari_abdomen.png",
  rarity: "",
  description: "Only the desperate eat this raw...",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Cooked Kuongatari Abdomen",
  layer: "l4 l5",
  mob: "Kuongatari",
  mobLink: "/bestiary/bestiary.html?page=65",
  image: "../items/mob_drops/images/kuongatari_abdomen_cooked.png",
  rarity: "",
  description: "Suprisingly tasty for such a small bug..",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Madokajack Bone",
  layer: "l3",
  mob: "Madokajack",
  mobLink: "/bestiary/bestiary.html?page=51",
  image: "../items/mob_drops/images/madokajack_bone.png",
  rarity: "",
  description: "Even their bones smell rancid.",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Madokajack Eye",
  layer: "l3",
  mob: "Madokajack",
  mobLink: "/bestiary/bestiary.html?page=51",
  image: "../items/mob_drops/images/madokajack_eye.png",
  rarity: "",
  description: "It looks so derpy without its body.",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Roasted Madokajack Eye",
  layer: "l3",
  mob: "Madokajack",
  mobLink: "/bestiary/bestiary.html?page=51",
  image: "../items/mob_drops/images/madokajack_eye_roasted.png",
  rarity: "",
  description: "I wonder how many people in Orth would like to eat this...",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Madokajack Poop",
  layer: "l3",
  mob: "Madokajack",
  mobLink: "/bestiary/bestiary.html?page=51",
  image: "../items/mob_drops/images/madokajack_poop.png",
  rarity: "",
  description: "Did I scare it so much that it pooped itself on death?",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Madokajack Scales",
  layer: "l3",
  mob: "Madokajack",
  mobLink: "/bestiary/bestiary.html?page=51",
  image: "../items/mob_drops/images/madokajack_scales.png",
  rarity: "",
  description: "Though hard, these scales are slimy and smell of feces!?",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Makihige Ink Sac",
  layer: "l4 l5",
  mob: "Makihige",
  mobLink: "/bestiary/bestiary.html?page=67",
  image: "../items/mob_drops/images/makihige_ink_sac.png",
  rarity: "",
  description: "With this you might be able to do something. Probably not though",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Makihige Shell",
  layer: "l4 l5",
  mob: "Makihige",
  mobLink: "/bestiary/bestiary.html?page=67",
  image: "../items/mob_drops/images/makihige_shell.png",
  rarity: "",
  description: "I hope I can make armor from this some day. But how?",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Makihige Tentacle",
  layer: "l4 l5",
  mob: "Makihige",
  mobLink: "/bestiary/bestiary.html?page=67",
  image: "../items/mob_drops/images/makihige_tentacle.png",
  rarity: "",
  description: "Seems useful. I better keep this...",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Man-toyer Fur",
  layer: "l1",
  mob: "Man-toyer",
  mobLink: "/bestiary/bestiary.html?page=7",
  image: "../items/mob_drops/images/mantoyer_fur.png",
  rarity: "",
  description: "Thickly furred, and very sturdy...",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Man-toyer Horns",
  layer: "l1",
  mob: "Man-toyer",
  mobLink: "/bestiary/bestiary.html?page=7",
  image: "../items/mob_drops/images/mantoyer_horns.png",
  rarity: "",
  description: "I could cut myself on these if I'm not careful.",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Raw Neritantan Meat",
  layer: "l2 l3",
  mob: "Neritantan",
  mobLink: "/bestiary/bestiary.html?page=40",
  image: "../items/mob_drops/images/neritantan_meat_raw.png",
  rarity: "",
  description: "Very tasty as they mostly eat Baracocha fruit. Do not get in between a Neritantan and a Baracocha fruit!",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Cooked Neritantan Meat",
  layer: "l2 l3",
  mob: "Neritantan",
  mobLink: "/bestiary/bestiary.html?page=40",
  image: "../items/mob_drops/images/neritantan_meat_cooked.png",
  rarity: "",
  description: "Very tasty as they mostly eat Baracocha fruit. Do not get in between a Neritantan and a Baracocha fruit!",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Octoliar Ink Sac",
  layer: "l5",
  mob: "Octoliar",
  mobLink: "/bestiary/bestiary.html?page=92",
  image: "../items/mob_drops/images/octoliar_ink_sac.png",
  rarity: "",
  description: "Dark at first, but after mixing it with the air it starts to glow!",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Octoliar Tentacle",
  layer: "l5",
  mob: "Octoliar",
  mobLink: "/bestiary/bestiary.html?page=92",
  image: "../items/mob_drops/images/octoliar_tentacle.png",
  rarity: "",
  description: "Although a little wet, it's as tough as a rock!",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Okibo Fur",
  layer: "l0 l1",
  mob: "Okibo",
  mobLink: "/bestiary/bestiary.html?page=1",
  image: "../items/mob_drops/images/okibo_fur.png",
  rarity: "",
  description: "Looks like it will keep me warm through the entire winter if needed.",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Raw Okibo Meat",
  layer: "l0 l1",
  mob: "Okibo",
  mobLink: "/bestiary/bestiary.html?page=1",
  image: "../items/mob_drops/images/okibo_meat_raw.png",
  rarity: "",
  description: "Usually found in Orth as a source of transportation of goods, Okibos are also a great source of food due to their large size.",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Cooked Okibo Meat",
  layer: "l0 l1",
  mob: "Okibo",
  mobLink: "/bestiary/bestiary.html?page=1",
  image: "../items/mob_drops/images/okibo_meat_cooked.png",
  rarity: "",
  description: "There is a ritual in Orth, for whenever a Black Whistle or White Whistle return from their plunge into the Abyss. The GuildHQ Head Chef butchers the Okibo they arrive on and prepare a giant feast for all.",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Onitsuchi Egg",
  layer: "l4 l5",
  mob: "Onitsuchi",
  mobLink: "/bestiary/bestiary.html?page=68",
  image: "../items/mob_drops/images/onitsuchi_egg.png",
  rarity: "",
  description: "Can be used as a cooking ingredient or mischievious acts of tomfoolery. Mother Onitsuchi does not look to happy...",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Onitsuchi Feather",
  layer: "l4 l5",
  mob: "Onitsuchi",
  mobLink: "/bestiary/bestiary.html?page=68",
  image: "../items/mob_drops/images/onitsuchi_feather.png",
  rarity: "",
  description: "Just a feather, innit?",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Onitsuchi Skull",
  layer: "l4 l5",
  mob: "Onitsuchi",
  mobLink: "/bestiary/bestiary.html?page=68",
  image: "../items/mob_drops/images/onitsuchi_skull.png",
  rarity: "",
  description: "Can be used as a fire starter when combined with a little steel. It seems sharp enough to put an eye out.",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Raw Onitsuchi Wing",
  layer: "l4 l5",
  mob: "Onitsuchi",
  mobLink: "/bestiary/bestiary.html?page=68",
  image: "../items/mob_drops/images/onitsuchi_wing_raw.png",
  rarity: "",
  description: "This meat seems delicious if cooked properly!",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Cooked Onitsuchi Wing",
  layer: "l4 l5",
  mob: "Onitsuchi",
  mobLink: "/bestiary/bestiary.html?page=68",
  image: "../items/mob_drops/images/onitsuchi_wing_cooked.png",
  rarity: "",
  description: "Can also be acquired from cooking This tastes delicious!",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Orb Piercer Face Fragments",
  layer: "l4",
  mob: "Orb Piercer",
  mobLink: "/bestiary/bestiary.html?page=69",
  image: "../items/mob_drops/images/orb_piercer_face_fragments.png",
  rarity: "",
  description: "I wonder if I collect enough, will I be able to see it as well? Probably just wishful thinking...",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Orb Piercer Spike",
  layer: "l4",
  mob: "Orb Piercer",
  mobLink: "/bestiary/bestiary.html?page=69",
  image: "../items/mob_drops/images/orb_piercer_spike.png",
  rarity: "",
  description: "Drops from the fiercely territorial Orb Piercer. Handle carefully! Its venom is very lethal.",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Raw Ottobas Meat",
  layer: "l2",
  mob: "Ottobas",
  mobLink: "/bestiary/bestiary.html?page=26",
  image: "../items/mob_drops/images/ottobas_meat_raw.png",
  rarity: "",
  description: "A thick layer of fat clings to the meat. Cooking it should help making it edible.",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Cooked Ottobas Meat",
  layer: "l2",
  mob: "Ottobas",
  mobLink: "/bestiary/bestiary.html?page=26",
  image: "../items/mob_drops/images/ottobas_meat_cooked.png",
  rarity: "",
  description: "This should be enough food to last for daaaaayyss!!",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Rinsipede Segments",
  layer: "l3",
  mob: "Rinsipede",
  mobLink: "/bestiary/bestiary.html?page=53",
  image: "../items/mob_drops/images/rinsipede_segments.png",
  rarity: "",
  description: "I've heard their body makes for a great fertiliser.",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Rock-walker Mandible",
  layer: "l2 l3",
  mob: "Rockwalker",
  mobLink: "/bestiary/bestiary.html?page=41",
  image: "../items/mob_drops/images/rockwalker_mandible.png",
  rarity: "",
  description: "The rockwalkers use these as their climbing gear, and its toughness sure looks the part.",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Rohana Powder",
  layer: "l2 l4",
  mob: "Rohana",
  mobLink: "/bestiary/bestiary.html?page=27",
  image: "../items/mob_drops/images/rohana_powder.png",
  rarity: "",
  description: "The closest thing to magical fairy dust.",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Rohana Tail",
  layer: "l2 l4",
  mob: "Rohana",
  mobLink: "/bestiary/bestiary.html?page=27",
  image: "../items/mob_drops/images/rohana_tail.png",
  rarity: "",
  description: "Can be used to make brewing stands or other useful relics...",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Sakuranbo Dust",
  layer: "l3",
  mob: "Sakuranbo",
  mobLink: "/bestiary/bestiary.html?page=55",
  image: "../items/mob_drops/images/sakuranbo_dust.png",
  rarity: "",
  description: "Careful! Ignites easily.",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Parasitic Watershrooms",
  layer: "l4",
  mob: "Shroombear",
  mobLink: "/bestiary/bestiary.html?page=71",
  image: "../items/mob_drops/images/parasitic_watershrooms.png",
  rarity: "",
  description: "Sucks nutrients from its host, releasing them back when the host is near death.",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Shroombear Meat",
  layer: "l4",
  mob: "Shroombear",
  mobLink: "/bestiary/bestiary.html?page=71",
  image: "../items/mob_drops/images/shroombear_meat_raw.png",
  rarity: "",
  description: "It's edible and dark in colour. Might smell like excrement if you don't clean it well...",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Cooked Shroombear Meat",
  layer: "l4",
  mob: "Shroombear",
  mobLink: "/bestiary/bestiary.html?page=71",
  image: "../items/mob_drops/images/shroombear_meat_cooked.png",
  rarity: "",
  description: "It's edible and dark in colour. Might smell like excrement if you don't clean it well...",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Bundle of Silkfang Silk",
  layer: "l1 l2",
  mob: "Silkfang",
  mobLink: "/bestiary/bestiary.html?page=9",
  image: "../items/mob_drops/images/bundle_of_silkfang_silk.png",
  rarity: "",
  description: "Most people don't enjoy getting stuck in this.",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Silkfang Eye",
  layer: "l1 l2",
  mob: "Silkfang",
  mobLink: "/bestiary/bestiary.html?page=9",
  image: "../items/mob_drops/images/silkfang_eye.png",
  rarity: "",
  description: "Rumor has it that a larger arachnid can stare back at you through this...",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Silkfang Silk",
  layer: "l1 l2",
  mob: "Silkfang",
  mobLink: "/bestiary/bestiary.html?page=9",
  image: "../items/mob_drops/images/silkfang_silk.png",
  rarity: "",
  description: "Somewhat fine silk with a large amount of tensile strength.",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Spikewalker Spike",
  layer: "l5",
  mob: "Spikewalker",
  mobLink: "/bestiary/bestiary.html?page=95",
  image: "../items/mob_drops/images/spikewalker_spike.png",
  rarity: "",
  description: "It may not look pointy, but don't let it poke ya!",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Spikewalker Meat",
  layer: "l5",
  mob: "Spikewalker",
  mobLink: "/bestiary/bestiary.html?page=95",
  image: "../items/mob_drops/images/spikewalker_meat.png",
  rarity: "",
  description: "Inedible, hard, rough, and gamey...",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Raw Spiralsquid",
  layer: "l1 l4",
  mob: "Spiralsquid",
  mobLink: "/bestiary/bestiary.html?page=10",
  image: "../items/mob_drops/images/spiralsquid_raw.png",
  rarity: "",
  description: "Seems like a great source of food!",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Cooked Spiralsquid",
  layer: "l1 l4",
  mob: "Spiralsquid",
  mobLink: "/bestiary/bestiary.html?page=10",
  image: "../items/mob_drops/images/spiralsquid_cooked.png",
  rarity: "",
  description: "Seems like a great source of food!",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Plant Matter",
  layer: "l1 l2 l4",
  mob: "Spittleshrub, Vinebinder, Vineblaster, Vinepoofer",
  mobLink: "/bestiary/bestiary.html?page=11",
  image: "../items/mob_drops/images/plant_matter.png",
  rarity: "",
  description: "Maybe I could use this to make my own plants, though they wouldn't do anything special without proper care..",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Spittleshrub Root",
  layer: "l1 l2 l4",
  mob: "Spittleshrub",
  mobLink: "/bestiary/bestiary.html?page=11",
  image: "../items/mob_drops/images/spittleshrub_root.png",
  rarity: "",
  description: "This looks like a pretty vital ingredient for some plants.",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Splitjaw Gunk",
  layer: "l1 l2 l3",
  mob: "Splitjaw",
  mobLink: "/bestiary/bestiary.html?page=12",
  image: "../items/mob_drops/images/splitjaw_gunk.png",
  rarity: "",
  description: "Yucky.",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Splitjaw Scales",
  layer: "l1 l2 l3",
  mob: "Splitjaw",
  mobLink: "/bestiary/bestiary.html?page=12",
  image: "../items/mob_drops/images/splitjaw_scales.png",
  rarity: "",
  description: "Can be used to make certain blocks.",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Spore Manta Powder",
  layer: "l5",
  mob: "Spore Manta",
  mobLink: "/bestiary/bestiary.html?page=96",
  image: "../items/mob_drops/images/sporemanta_powder.png",
  rarity: "",
  description: "The furthest thing to magical fairy dust.",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Spore Manta Wing",
  layer: "l5",
  mob: "Spore Manta",
  mobLink: "/bestiary/bestiary.html?page=96",
  image: "../items/mob_drops/images/sporemanta_wing.png",
  rarity: "",
  description: "Leathery wing laced in a poisonous powder",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Squidfly Brain",
  layer: "l3",
  mob: "Squidfly",
  mobLink: "/bestiary/bestiary.html?page=57",
  image: "../items/mob_drops/images/squidfly_brain_raw.png",
  rarity: "",
  description: "Eating it raw might not be the brighest idea I've come up with...",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Cooked Squidfly Brain",
  layer: "l3",
  mob: "Squidfly",
  mobLink: "/bestiary/bestiary.html?page=57",
  image: "../items/mob_drops/images/squidfly_brain_cooked.png",
  rarity: "",
  description: "Perhaps I will become smarter if I consume this brain?",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Stinger Horn",
  layer: "l2 l4 l5",
  mob: "Stinger",
  mobLink: "/bestiary/bestiary.html?page=43",
  image: "../items/mob_drops/images/stinger_horn.png",
  rarity: "",
  description: "The beak of a Stinger sharp enough to pierce flesh.",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Stinger Wing",
  layer: "l2 l4 l5",
  mob: "Stinger",
  mobLink: "/bestiary/bestiary.html?page=43",
  image: "../items/mob_drops/images/stinger_wing.png",
  rarity: "",
  description: "A very thin, yet surprisingly flexible piece of flesh",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Stingerhead Eye",
  layer: "l5",
  mob: "Stingerhead",
  mobLink: "/bestiary/bestiary.html?page=98",
  image: "../items/mob_drops/images/stingerhead_eye.png",
  rarity: "",
  description: "Its eye was almost fused into its armor.",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Stingerhead Flesh",
  layer: "l5",
  mob: "Stingerhead",
  mobLink: "/bestiary/bestiary.html?page=98",
  image: "../items/mob_drops/images/stingerhead_flesh.png",
  rarity: "",
  description: "This is definetly not edible! It reeks of burned dried vomit, much like Nanachi's Netherworld Stew.",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Stingerhead Scale",
  layer: "l5",
  mob: "Stingerhead",
  mobLink: "/bestiary/bestiary.html?page=98",
  image: "../items/mob_drops/images/stingerhead_scale.png",
  rarity: "",
  description: "It is said to be the toughest known material in the Abyss. Perhaps I can upgrade my armour with this?",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Swarmshocker Charged Powder",
  layer: "l4 l5",
  mob: "Swarmshocker, Swarmhoarder",
  mobLink: "/bestiary/bestiary.html?page=75",
  image: "../items/mob_drops/images/swarmshocker_charged_powder.png",
  rarity: "",
  description: "This stores an impressive amount of energy!",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Swarmhoarder Jelly",
  layer: "l5",
  mob: "Swarmhoarder",
  mobLink: "/bestiary/bestiary.html?page=99",
  image: "../items/mob_drops/images/swarmshocker_jelly.png",
  rarity: "",
  description: "Very sticky, almost like some sort of resin. Tastes very watery...",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Tachikatana Claw",
  layer: "l4 l5",
  mob: "Tachikatana",
  mobLink: "/bestiary/bestiary.html?page=76",
  image: "../items/mob_drops/images/tachikatana_claw.png",
  rarity: "",
  description: "Striking it in a particular way emits a shockwave..",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Tachikatana Leg",
  layer: "l4 l5",
  mob: "Tachikatana",
  mobLink: "/bestiary/bestiary.html?page=76",
  image: "../items/mob_drops/images/tachikatana_leg.png",
  rarity: "",
  description: "Tastes like crab! Too tough to cook!",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Tachikatana Scale",
  layer: "l4 l5",
  mob: "Tachikatana",
  mobLink: "/bestiary/bestiary.html?page=76",
  image: "../items/mob_drops/images/tachikatana_scale.png",
  rarity: "",
  description: "A shiny scale knocked off the Tachikatana! They're rumored to be one of the most waterproof materials in the Abyss.",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Tesuchi Scales",
  layer: "l2",
  mob: "Tesuchi",
  mobLink: "/bestiary/bestiary.html?page=31",
  image: "../items/mob_drops/images/tesuchi_scales.png",
  rarity: "",
  description: "Obtained by slaughtering a Tesuchi in Edge of the Abyssand Forest of Temptation. It changes colour even in your hand.",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Tesuchi Tail",
  layer: "l2",
  mob: "Tesuchi",
  mobLink: "/bestiary/bestiary.html?page=31",
  image: "../items/mob_drops/images/tesuchi_tail.png",
  rarity: "",
  description: "Obtained by cutting of the Tail in the Edge of the Abyssand Forest of Temptation. It is said it tastes like rubber. is strangely very squishy!...",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Cooked Tesuchi Tail",
  layer: "l2",
  mob: "Tesuchi",
  mobLink: "/bestiary/bestiary.html?page=31",
  image: "../items/mob_drops/images/tesuchi_tail.png",
  rarity: "",
  description: "Obtained by cutting of the Tail in the Edge of the Abyss<yellow>and Forest of Temptation. tastes more like chicken now. it's not so squishy anymore...",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Tosubachi",
  layer: "l2",
  mob: "Tesuchi",
  mobLink: "/bestiary/bestiary.html?page=31",
  image: "../items/mob_drops/images/tosubachi.png",
  rarity: "",
  description: "A dried Tesuchi. Seen as a delicacy, its toughness is made up for by its unique flavor.",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Titanjaw Pearl",
  layer: "l5",
  mob: "Titanjaw",
  mobLink: "/bestiary/bestiary.html?page=102",
  image: "../items/mob_drops/images/titanjaw_pearl.png",
  rarity: "",
  description: "Why do I feel like I am haunted...",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Titanjaw Scale",
  layer: "l5",
  mob: "Titanjaw",
  mobLink: "/bestiary/bestiary.html?page=102",
  image: "../items/mob_drops/images/titanjaw_scale.png",
  rarity: "",
  description: "Might be useful to craft gear with if I collect enough.",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Uibuta Tooth",
  layer: "l4 l5",
  mob: "Uibuta",
  mobLink: "/bestiary/bestiary.html?page=77",
  image: "../items/mob_drops/images/uibuta_tooth.png",
  rarity: "",
  description: "It is fairly big, but suprisingly blunt...",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Raw Uibuta Meat",
  layer: "l4 l5",
  mob: "Uibuta",
  mobLink: "/bestiary/bestiary.html?page=77",
  image: "../items/mob_drops/images/uibuta_meat_raw.png",
  rarity: "",
  description: "A thick layer of fat clings to the meat. Cooking it should help making it edible.",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Cooked Uibuta Meat",
  layer: "l4 l5",
  mob: "Uibuta",
  mobLink: "/bestiary/bestiary.html?page=77",
  image: "../items/mob_drops/images/uibuta_meat_cooked.png",
  rarity: "",
  description: "This should be enough food to last for daaaaayyss!!",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Virinsipede Antlers",
  layer: "l5",
  mob: "Virinsipede",
  mobLink: "/bestiary/bestiary.html?page=104",
  image: "../items/mob_drops/images/virinsipede_antlers.png",
  rarity: "",
  description: "Blazing hot, just like the Virinsipede's rage.",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Virinsipede Segments",
  layer: "l5",
  mob: "Virinsipede",
  mobLink: "/bestiary/bestiary.html?page=104",
  image: "../items/mob_drops/images/virinsipede_segments.png",
  rarity: "",
  description: "I've heard their body makes for a great fertiliser.",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Woodcrier Horn",
  layer: "l2",
  mob: "Woodcrier",
  mobLink: "/bestiary/bestiary.html?page=35",
  image: "../items/mob_drops/images/woodcrier_horn.png",
  rarity: "",
  description: "Its hard and solid... I can build structures with this.",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Yomotsubi Wing",
  layer: "l3",
  mob: "Yomotsubi",
  mobLink: "/bestiary/bestiary.html?page=58",
  image: "../items/mob_drops/images/yomotsubi_wing.png",
  rarity: "",
  description: "A sturdy, metallic wing. Perhaps i can mold this into something...",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Shiratsubi Wing",
  layer: "l5",
  mob: "Shiratsubi",
  mobLink: "/bestiary/bestiary.html?page=94",
  image: "../items/mob_drops/images/shiratsubi_wing.png",
  rarity: "",
  description: "A sturdy, metallic wing. Perhaps i can mold this into something...",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Yomotsubi Abdomen",
  layer: "l3 l5",
  mob: "Yomotsubi, Shiratsubi",
  mobLink: "/bestiary/bestiary.html?page=58",
  image: "../items/mob_drops/images/yomotsubi_abdomen_raw.png",
  rarity: "",
  description: "Perhaps this could be cooked...",
  trades: [],
  tips: [],
  recipes: []
},
{
  name: "Cooked Yomotsubi Abdomen",
  layer: "l3 l5",
  mob: "Yomotsubi, Shiratsubi",
  mobLink: "/bestiary/bestiary.html?page=58",
  image: "../items/mob_drops/images/yomotsubi_abdomen_cooked.png",
  rarity: "",
  description: "Tastes suprisingly good.",
  trades: [],
  tips: [],
  recipes: []
},
/*
{
  name: "Pluh Item",
  layer: "l5",
  mob: "Pluh Mob",
  mobLink: "/bestiary/bestiary.html?page=67",
  image: "../items/mob_drops/images/pluh.png",
  rarity: "",
  description: "pluh",
  trades: [],
  tips: [],
  recipes: []
}
*/

];